language: r
sudo: required
dist: trusty
r:
- release
deploy.skip_cleanup: true
cache:
- packages
- ccache
r_github_packages:
- r-lib/covr
- r-spatial/sf
- r-spatial/stars
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
    - libprotobuf-dev
    - protobuf-compiler
    - libv8-3.14-dev
    - libjq-dev
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libspatialite-dev
    - libgdal-dev
    - libjson-c-dev
    - libnetcdf-dev
    - netcdf-bin
before_install:
- sudo apt-get update
- sudo apt-get remove python3-pip
- sudo apt-get install python3-pip
- sudo -H pip3 install --upgrade pip
#- sudo apt-get install libffi-dev libssl-dev
#- wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz
#- tar -zxf openssl-1.1.1d.tar.gz && cd openssl-1.1.1d
#- ./config
#- sudo apt install make gcc
#- make test
#- sudo mv /usr/bin/openssl ~/tmp
#- sudo make install
#- sudo ln -s /usr/local/bin/openssl /usr/bin/openssl
#- sudo ldconfig
#- openssl version
#- cd /home/travis/build/csaybar/rgee
- R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
- R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
- R -q -e 'remotes::install_github("ropenscilabs/tic", upgrade = "always"); print(tic::dsl_load());
  tic::prepare_all_stages()'
- R -q -e 'tic::before_install()'
install:
- sudo -H pip3 install earthengine-api==0.1.175
- sudo -H pip3 install coveralls
- sudo -H pip3 install oauth2client
- sudo -H pip3 install selenium
- sudo -H pip3 install bs4
- sudo -H pip3 install pysmartDL
- sudo -H pip3 install requests_toolbelt
- R -q -e 'tic::install()'
script:
- R -q -e 'tic::script()'
after_success:
- R -q -e 'covr::codecov(quiet = FALSE)'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
