# DO NOT CHANGE the "init" and "install" sections below
image: Visual Studio 2015

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin"
  R_CHECK_ARGS: "--no-manual --as-cran --no-examples --no-tests"
  matrix:
    - PYTHON: "C:\\Python35"
      RETICULATE_PYTHON: "C:\\Python35"

matrix:
  fast_finish: true

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'


install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
build_script:
  - "%PYTHON%\\python.exe -m pip install setuptools numpy earthengine-api coveralls"
  - "%PYTHON%\\python.exe -m pip install oauth2client selenium bs4 requests_toolbelt"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

# Adapt as necessary starting from here
on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
#environment:
# The example below will not work for your repository,
# you need to encrypt your own token.
# Please follow https://ci.appveyor.com/tools/encrypt .
#GITHUB_PAT:
#  secure: VXO22OHLkl4YhVIomSMwCZyOTx03Xf2WICaVng9xH7gISlAg8a+qrt1DtFtk8sK5

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
